# Generated by Django 5.0 on 2024-04-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collection_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='gradInt',
            field=models.IntegerField(default=2, verbose_name='gradient id'),
        ),
    ]
