# Generated by Django 5.0 on 2024-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_quiz_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='collection_id',
            field=models.IntegerField(default=1, verbose_name='collection id'),
        ),
    ]
