# Generated by Django 5.0 on 2023-12-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='premium status'),
        ),
    ]
