# Generated by Django 5.0 on 2024-01-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0005_customuser_locale_alter_customuser_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=26, null=True, unique=True, verbose_name='username'),
        ),
    ]
