# Generated by Django 5.0 on 2024-01-20 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0007_customuser_changedusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_count', models.IntegerField(default=0, verbose_name='stars count')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('emoji', models.CharField(max_length=5, verbose_name='emoji')),
                ('words', models.JSONField(default=list, verbose_name='words')),
                ('language', models.CharField(max_length=50, verbose_name='language')),
                ('isPublic', models.BooleanField(default=True, verbose_name='is public')),
                ('lastEdited', models.DateTimeField(auto_now_add=True, verbose_name='last edited')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='users', to='lingauth.collection'),
        ),
    ]
