# Generated by Django 5.0 on 2024-01-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0008_collection_customuser_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='isDefault',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
    ]
