# Generated by Django 5.0 on 2024-02-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0011_collection_isforked'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='comments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(default='my fancy dictionary', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='collection',
            name='socials',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.CharField(default='dict', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='collection',
            name='whoForked',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='collection',
            name='whoStarred',
            field=models.JSONField(default=list),
        ),
    ]
