# Generated by Django 5.0 on 2024-02-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0012_collection_comments_collection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='isOfficial',
            field=models.BooleanField(default=False, verbose_name='is forked'),
        ),
    ]
