# Generated by Django 5.0 on 2024-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0013_collection_isofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='isMobile',
            field=models.BooleanField(default=False, verbose_name='is mobile'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='isOfficial',
            field=models.BooleanField(default=False, verbose_name='is official'),
        ),
    ]
