# Generated by Django 5.0 on 2024-02-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0015_remove_customuser_collections_delete_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=5),
        ),
    ]
