# Generated by Django 5.0 on 2024-02-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0016_customuser_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=30),
        ),
    ]
