# Generated by Django 5.0 on 2024-04-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0017_alter_customuser_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='locale',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='locale'),
        ),
    ]
