# Generated by Django 5.0 on 2024-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0018_alter_customuser_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quiz_data',
            field=models.JSONField(default=list, verbose_name='quiz data'),
        ),
    ]
