# Generated by Django 5.0 on 2024-05-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0019_customuser_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.JSONField(default=list, verbose_name='notifications data'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved_items',
            field=models.JSONField(default=list, verbose_name='saved items'),
        ),
    ]
