# Generated by Django 5.0 on 2024-05-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0020_customuser_notifications_customuser_saved_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='old_notifications',
            field=models.JSONField(default=list, verbose_name='notifications data'),
        ),
    ]
