# Generated by Django 5.0 on 2024-05-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0021_customuser_old_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity',
            field=models.JSONField(default=list, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
