# Generated by Django 5.0 on 2024-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0022_customuser_activity_customuser_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_week_data',
            field=models.JSONField(default=list, verbose_name='current_week'),
        ),
    ]
