# Generated by Django 5.0 on 2024-06-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingauth', '0023_customuser_current_week_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='greenWall',
            field=models.JSONField(default=list, verbose_name='github green wall'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastNicknameChange',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last edited'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastPurchaseDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last edited'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastRefillDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='last 30 refill'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paymentMethods',
            field=models.JSONField(default=list, verbose_name='card details'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='studyPreference',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='studyProgress',
            field=models.JSONField(default=list, verbose_name='official sets finished'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_week_data',
            field=models.JSONField(default=[{'day': 'Monday', 'hasPassed': False, 'isToday': False, 'user_activity': False}, {'day': 'Tuesday', 'hasPassed': False, 'isToday': True, 'user_activity': False}, {'day': 'Wednesday', 'hasPassed': False, 'isToday': False, 'user_activity': False}, {'day': 'Thursday', 'hasPassed': False, 'isToday': False, 'user_activity': False}, {'day': 'Friday', 'hasPassed': False, 'isToday': False, 'user_activity': False}, {'day': 'Saturday', 'hasPassed': False, 'isToday': False, 'user_activity': False}, {'day': 'Sunday', 'hasPassed': False, 'isToday': False, 'user_activity': False}], verbose_name='current_week'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='notifications',
            field=models.JSONField(default=[{'date': '2024-06-25 09:39:16.086874+00:00', 'item_id': 0, 'item_name': 'Hoşgeldiniz!', 'notification_emoji': '⭐', 'type': 'welcome'}], verbose_name='notifications data'),
        ),
    ]
